#!/usr/bin/env python3

YES = "Yes"  # type: str
NO = "No"  # type: str

def is_symmetrical(S: str):
    N = len(S)
    for i in range(N):
        if S[i] != S[N-i-1]:
            return False
    return True

# K < 2Nの場合
def can_solve(S, K):
    N = len(S)
    S_inv = S[::-1]
    if K <= N:
        T = S_inv[N-K:]
    else:
        T = S_inv[:K-N] + S_inv
    new_S1 = S + T
    new_S2 = T + S
    return is_symmetrical(new_S1) and is_symmetrical(new_S2)


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    T = int(input())
    for t in range(T):
        N, K = map(int, input().split())
        S = input()
        if (K // (2*N)) % 2 == 1:
            S = S[::-1]
        if can_solve(S, K % (2*N)):
            print(YES)
        else:
            print(NO)

if __name__ == '__main__':
    main()
